# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: tretry 0.0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "tretry"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Kasper Stöckel"]
  s.date = "2014-11-21"
  s.description = "A library for doing retries in Ruby with timeouts, analysis of errors, waits between tries and more."
  s.email = "k@spernj.org"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = Dir["{lib}/**/*"] + ["Rakefile"]
  s.homepage = "http://github.com/kaspernj/tretry"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.0"
  s.summary = "A library for doing retries in Ruby with timeouts, analysis of errors, waits between tries and more."

  s.add_development_dependency "rspec", "2.8.0"
  s.add_development_dependency "rdoc", "3.12"
  s.add_development_dependency "bundler", "1.0.0"
end
